### ISSUE TITLE
Unable to replicate result for Figure 8 (Canadian bill voting network)

### ISSUE THREAD

**Issue by brytlao** [shenyangHuang/LAD#1]
I am unable to replicate your result for Figure 8 (Canadian bill voting network).
I tried both default settings and making some corrections (listed below).
Please let me know if I used the wrong settings.
Thanks for your time!
![canVote](https://user-images.githubusercontent.com/22209474/100182522-2ddf4d00-2f20-11eb-8e5d-c6368f1e74b5.png)

What I did:
1. modified: datasets/canVote_loader.py
68: u = values[1]       
69: v = values[2]

2. modified: Anomaly_Detection.py
741: window1 = 2
742: window2 = 4
743: initial_window = 4

3. run the notebook
!python Real_Command.py -d canVote -n 6

**Comment by shenyangHuang** [comment]
Hi, thanks for your comment! For this experiment, we mention in the paper that the top 338 singular values are used (= the number of seats in the house of commons in Canada). I have also updated the code for the correct window sizes. If you see any issues, please feel free to reach out to my email as well and I will address it as quickly as possible.

**Comment by brytlao** [comment]
Oh right! That did the trick. Thanks!
